name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab=4.3.0
  - papermill=2.6.0
  - voila=0.5.8
  - nb_conda_kernels=2.5.1
  - ipywidgets=8.1.5
  - dash==2.18.2
  - jupyterlab-lsp=5.1.0
  - jupyterlab_code_formatter=3.0.2
  - python-lsp-server=1.12.2
  - ruff=0.9.10
  - ipydatagrid=1.4.0